import Head from "next/head";
import Layout from "../components/Layout";

export default function Home() {
  return (

    <div style={{ margin: '2rem' }}>
      <Head>
        <title>Base de datos LAOF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout
        title="Home"
        home
      >
        <section >
          {/* <Button>
            a
          </Button> */}
          <h1>Base de Datos de LAOF</h1>

          <p>[Introduction]</p>
          <p>
            (Website made in NextJS, with MongoDB)
          </p>
        </section>
      </Layout>



    </div>
  );
}
