import Head from "next/head";
import Prueba from '../pages/components/Prueba'
import { useState, useEffect } from "react";

export default function Home() {

  const [morfologiamandibulas, setMorfologiamandibulas] = useState([])
  const [pesomandibulas, setPesomandibulas] = useState([])
  const [cargaDatos, setCargaDatos] = useState(false);
  const [limitMorfo,setLimitMorfo] = useState(2)
  const [limitPesos,setLimitPesos]= useState(2)

  const getData = async () => {
    let dev = process.env.NODE_ENV !== 'production';
    // Cambiar para tener las variables en env
    //const DEV_URL = process.env.DEV_URL;
    //const PROD_URL = process.env.PROD_URL;

    let DEV_URL = "http://localhost:3000" 
    let PROD_URL = "https://laofdb.vercel.app/"

    // Cada uno se puede cargar por separado, poniendo en headers el nombre de la collección
    let response = await fetch(`${dev ? DEV_URL : PROD_URL}/api/muestras`, {headers:{collection: "morfologiamandibulas", limit : limitMorfo} } )
    let data = await response.json()
    console.log("--",data.message,"--")

    setMorfologiamandibulas(data.message)
    //console.log("--",data,"--")
    
    let response2 = await fetch(`${dev ? DEV_URL : PROD_URL}/api/muestras`, {headers:{collection: "pesomandibulas",limit : limitPesos} } )
    let data2 = await response2.json()
    console.log("--",data2.message,"--")
    setPesomandibulas(data2.message)
  }

  useEffect(() =>{
    if (cargaDatos)
      getData()
  },[cargaDatos])

  useEffect(() =>{
    console.log("1->",morfologiamandibulas,pesomandibulas,"<-1")
    console.log("2->",typeof morfologiamandibulas,typeof pesomandibulas,"<-2")
    morfologiamandibulas.map(e => {console.log(e)})

  },[morfologiamandibulas, pesomandibulas])

  const handleLoadData = () => {
    setCargaDatos(!cargaDatos)
  }

  //<Prueba morfologiasMandibulas={morfologiamandibulas} dataPesomandibulas={pesomandibulas}></Prueba>

  return (

    <div style={{margin:'2rem'}}>
      <Head>
        <title>Base de datos LAOF</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Base de Datos de LAOF</h1>
      <button className="btn btn-primary" onClick={handleLoadData}>
          Cargar BD
      </button>
      
      <div>
        <label for='morfo'>Total de datos para Morfologías:</label>
        <input
        className="form-control"
        type='number' 
        id="morfo"
        min='0'
        value={limitMorfo} 
        onChange={e => setLimitMorfo(e.target.value)}
        >
        </input>
        <label for=''>Búscar por ID:</label>
        <input
        className="form-control"
        value={limitPesos} 
        onChange={e => setLimitPesos(e.target.value)}
        >
        </input>
      </div>
     

      <p>Aquí se pondrán los campos de búsqueda definidos por hooks</p>
      <p>Se podrá elegir entre diferentes BD y hacer búsqueda por ID, nombre, etc.</p>

      <main className="container">
        {cargaDatos ? 
            <Prueba morfologiasMandibulas={morfologiamandibulas} dataPesomandibulas={pesomandibulas}></Prueba>
            :
            <h1>Pulsa 'Cargar BD' para ver resultados</h1>
        }


      </main>
   
     
    </div>
  );
}
